"use client"

import { use } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Bot, LineChart, Network, GitPullRequest, ArrowRightLeft } from "lucide-react"

export default function SprintAnalyzerPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params)
  
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Sprint {resolvedParams.id} Deep Dive</h1>
          <p className="text-muted-foreground mt-1">Detailed metrics, anomalies, and AI analysis.</p>
        </div>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        {/* Main Analysis Column */}
        <div className="col-span-2 space-y-6">
          <Card className="border-t-4 border-t-purple-500 shadow-md">
            <CardHeader className="flex flex-row items-center gap-3">
              <Bot className="h-6 w-6 text-purple-500" />
              <div>
                <CardTitle>AI Sprint Analyst Report</CardTitle>
                <p className="text-sm text-muted-foreground">Generated by Claude 3.5 Sonnet</p>
              </div>
            </CardHeader>
            <CardContent className="space-y-4 prose dark:prose-invert">
              <div className="p-4 bg-muted/30 rounded-lg">
                <h4 className="text-sm font-semibold flex items-center mb-2"><LineChart className="mr-2 h-4 w-4" /> The Narrative</h4>
                <p className="text-sm">The team committed to 40 story points and delivered 32. A critical bottleneck emerged mid-sprint around backend API dependencies which impacted 3 frontend tasks. QA cycle times were 20% faster than historical averages, suggesting improved test automation.</p>
              </div>
              <div className="p-4 bg-red-500/10 border border-red-500/20 rounded-lg text-red-900 dark:text-red-300 pointer-events-none">
                <h4 className="text-sm font-semibold flex items-center mb-2"><Network className="mr-2 h-4 w-4" /> Root Cause Analysis</h4>
                <p className="text-sm">Missed goal primarily caused by Task #3492 (Auth Refactoring) which experienced massive scope creep. It was active for 8 days (avg is 2.4 days).</p>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle>Work Item Timeline & Transitions</CardTitle>
            </CardHeader>
            <CardContent className="h-64 flex items-center justify-center border-t bg-muted/5">
              <span className="text-muted-foreground"><ArrowRightLeft className="h-8 w-8 mx-auto mb-2 opacity-50" /> Transition Diagram Pipeline Placeholder</span>
            </CardContent>
          </Card>
        </div>

        {/* Sidebar Info Column */}
        <div className="col-span-1 space-y-6">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Risk Radar</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="flex items-start gap-3 p-3 bg-orange-500/10 rounded-md border border-orange-500/20">
                <GitPullRequest className="text-orange-500 mt-1 h-5 w-5" />
                <div>
                  <p className="font-semibold text-sm">PR Reviews Bottleneck</p>
                  <p className="text-xs text-muted-foreground">Dev A has 6 pending reviews.</p>
                </div>
              </div>
            </CardContent>
          </Card>
          
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Assignee Performance</CardTitle>
            </CardHeader>
            <CardContent className="h-48 flex items-center justify-center bg-muted/5 border-t">
               <span className="text-xs text-muted-foreground">Radar Chart Placeholder</span>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  )
}
